### ISSUE TITLE
Unable to connect to T1011 model. 

### ISSUE THREAD

**Issue by ghost** [sebmos/node-eufy-api#1]
Hello Sebastian!
First of all thanks for the node port. I want to address an issue with the T1011 model. Credentials and fetching device information are working great. Unfortunately I receive the following error when I attempt to connect with a T1011 bulb.

>Socket closed (with error) during connection process - not attempting restart

followed by

>(node:19033) UnhandledPromiseRejectionWarning: Error: Unable to connect to device. Are you on the same WiFi network?
    at Socket.<anonymous> (/home/dogukan/Projects/eufy-test/node_modules/node-eufy-api/lib/tcp-socket.js:86:28)
    at Socket.emit (events.js:188:13)
    at TCP._handle.close (net.js:610:12)

However, the client and the bulb are in the same network. I am running node version 11.6.0 on Linux and used both, the CLI variant and programmatically interface.

**Comment by sebmos** [comment]
@DogukanB, the stack trace suggests that the error is coming from the initial socket connection attempt, before the initial state check. 

When running the CLI, after logging in, you'll see a list of devices, with some data next to it. Can you do three things, please:
1. Can you verify that you're on the latest version of the library (0.0.3)?
2. Take the IP Address that's shown there and ping it.
3. Can you post a full console output (Starting with "Logged in!")?

**Comment by ghost** [comment]
Hello @sebmos ,
according to the package.json I am running 0.0.3. Pinging the bulb does work. The stacktrace however has changed, which is odd.
>Loading devices
Logged in!
? Choose device Bedroom (Model: T1011, Code: 209108B130454E9B, IP Address: 192.168.8.102)
(node:15543) UnhandledPromiseRejectionWarning: TypeError: response.getBulbinfo(...).getPacket(...).getInfo is not a function
    at LightBulb.<anonymous> (/home/dogukan/Projects/check/node_modules/node-eufy-api/lib/device-light-bulb.js:88:67)
    at step (/home/dogukan/Projects/check/node_modules/node-eufy-api/lib/device-light-bulb.js:45:23)
    at Object.next (/home/dogukan/Projects/check/node_modules/node-eufy-api/lib/device-light-bulb.js:26:53)
    at fulfilled (/home/dogukan/Projects/check/node_modules/node-eufy-api/lib/device-light-bulb.js:17:58)
(node:15543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sebmos** [comment]
Hey @DogukanB,

It appears there are two different issues at play here.

The first one appears to be more or less what the error message said - the light bulb couldn't be reached, although the given reason might be wrong. To clarify:
* Do you use a WiFi extender? (And are the client & light connected to different actual routers?)
* Is it at all possible your light bulb was simply unreachable/unconnected to power?

The error second error is very specific and helpful, and I think I found a solution. I've pushed an update that should hopefully fix it - can you try & check out this repo, run `npm install &&  npm run build && npm run cli` and see what happens now?

**Comment by ghost** [comment]
Hey @sebmos 
I am not using any kind of extender, bulb and client are connected to the same router, same access point and are in the same network. I was able to ping it, but I think the problem has been resolved by "restarting" the bulb (cutting the power off manually over a light switch), which I did yesterday before I posted the new stack trace. However it was controllable over Google Home and the official eufy mobile application.

Regarding to the new update, I am able to connect with the bulb and can see the current brightness but setting it does not work. Here is a sample I wrote 

```
import {loadDevices,Device,createDevice,Model } from "./index";
loadDevices("myemail","mypassword").then((dev:Device[])=>{
    const lightBulb = createDevice(Model.T1011, dev[0].code, dev[0].ipAddress);
    lightBulb.connect().then(()=>{
        console.log('isPowerOn()  ' + (lightBulb.isPowerOn() ? 'on' : 'off'));
        if (lightBulb.supportsBrightness()) {
            console.log('getBrightness() ' + lightBulb.getBrightness());
            lightBulb.setBrightness(10).then(newBrightness => {
                console.log('The brightness is now set to:', newBrightness);
            });
        }
    });
})
```
and this prints

```
>node-eufy-api@0.0.3 build:tsc /home/dogukan/node-eufy-api
>tsc

Loading devices
(node:23283) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
isPowerOn()  on
getBrightness() 100
Socket closed - attempting restart
The brightness is now set to: 100
```


There is by the way a small bug in the cli.ts, where the ternary operator is in the wrong order and consequently is disabling the menu option to change the properties of a connected device.

```			
disabled: device.isPowerOn() ? 'Turn on first' : undefined
```
Further below, the validation of the brightness input, the parseInt with a radix 2 is expecting a binary number rather than a decimal number.

Here is the same procedure but with the minor changes described above.
```

Loading devices
Logged in!

? Choose device Bedroom (Model: T1011, Code: 209108B130454E9B, IP Address: 192.168.8.102)

(node:24811) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
? Options Change brightness (currently 100/100)

? Enter brightness (between 0 and 100) 1010010
Socket closed - attempting restart
Brightness is now 100

? Options (Use arrow keys)
❯ Turn off 
  Change brightness (currently 100/100) 
  Back to Menu 
```

**Comment by sebmos** [comment]
Hey @DogukanB,

Thanks for confirming the restart - I'll put that into the Troubleshooting section.

I fixed both bugs (I hope) - can you give it another try?

**Comment by ghost** [comment]
Hello @sebmos ,
I gave it another try but the socket is still being closed

```
? Choose device Bedroom (Model: T1011, Code: 209108B130454E9B, IP Address: 192.168.8.102)
? Options Change brightness (currently 100/100)
? Enter brightness (between 0 and 100) 30
Socket closed - attempting restart
Brightness is now 100
? Options (Use arrow keys)
❯ Turn off 
  Change brightness (currently 100/100) 
  Back to Menu 
```

**Comment by sebmos** [comment]
Hey @DogukanB,

Thanks, I think we're getting closer. :-) I pushed another bug fix.

Btw, just to verify: Can you also try turning the light bulb on/off?

**Comment by ghost** [comment]
Hey @sebmos ,
thanks, the issue with turning it on or off does remain but changing the brightness does work now

**Comment by sebmos** [comment]
That's great news @DogukanB!

What seems to be the error with turning on/off? Is it the same socket-closing problem, with nothing happening?

**Comment by ghost** [comment]
Well, there is no error apparently. Here is what the CLI looks like
```
Loading devices
Logged in!

? Choose device Bedroom (Model: T1011, Code: 209108B130454E9B, IP Address: 192.168.8.138)
? Options Turn on
Power is now off
? Options (Use arrow keys)
❯ Turn on 
  - Change brightness (currently 0/100) (Turn on first)
  Back to Menu 
```

**Comment by sebmos** [comment]
Thanks @DogukanB,

This is now getting quite tricky without a device to test. :-D

I pushed another change - can you check again?

**Comment by DogukanB** [comment]
Many many many thanks for the last two weeks of your help. It does work now. If you need something, just leave a me a direct message :-D

**Comment by ghost** [comment]
Many many many thanks for the last two weeks of your help. It does work now. If you need something, just leave me a direct message :-D

**Comment by sebmos** [comment]
Amazing - I'll push a new version 0.0.5 and update the README.md accordingly.

Thanks for your help & patience!
