### ISSUE TITLE
Request support for Lumos 2.0

### ISSUE THREAD

**Issue by t3b4n** [sebmos/node-eufy-api#21]
Hi,

I have a Eufy Lumos Smart Bulb 2.0 White & Color (model code T1018). The bulb doesn't appear in Homebridge's devices using the current version of the plugin. 

I thought it was the same model code as T1013, but only knew it was different once the bulbs arrived home (the seller doesn't list the model code in its page). Is there a chance to add support for this device in the api?

I tried modifying the plugin files in homebridge, adding the T1018 model in the same categories as T1013, but had no effect, the bulb doesn't appear in the available devices. I also ran the cli commands to check the devices under my account, but I receive a "No devices found, exiting" message.

Thanks in advance,
Esteban.

**Comment by sebmos** [comment]
Hey,

I added support on the ["T1018" branch](https://github.com/sebmos/node-eufy-api/tree/T1018) of this package. Can you check out that branch and check if it works? If you do, please make sure to test the various features and let me know if all of them work as expected!

If this works, I'll merge support into the main branch.

**Comment by t3b4n** [comment]
Hi, Sebastian.

I pulled the latest code and did a checkout to branch "origin/T1018". After that I installed dependencies, built and ran the cli, which requested for my credentials. Once I gave them, I received the following lines as response:

(base) t3b4n@*** node-eufy-api % npm run cli

> node-eufy-api@0.4.0 cli
> node lib/cli.js

? Eufy account email address e***@**.com
? Eufy account password [hidden]
Logging in
Loading devices
Logged in, devices loaded
? Save credentials locally for future use? Yes
**No devices found, exiting**

**Comment by t3b4n** [comment]
If it helps, in [HomeAssistant wiki](https://www.home-assistant.io/integrations/eufy/) I found an API call that's actually returning my device information as follows: 

curl -H "Content-Type: application/json" \
   -d '{"client_id":"eufyhome-app", "client_Secret":"GQCpr9dSp3uQpsOMgJ4xQ", "email":"e***@***.com", "password":"*******"}' \
   https://home-api.eufylife.com/v1/user/email/login

This returns a token, which is used in the next command:

curl -H token:******* -H category:Home \
   https://home-api.eufylife.com/v1/device/list/devices-and-groups

This returns a json with the devices:

{
    "res_code":1,
    "message":"",
    "items":[
        {
            "item_type":0,
            "device":
            {
                "id":"ebc6e58*******xsq",
                "sn":"",
                "name":"Lumos 2.0 White \u0026 Color",
                "alias_name":"Luz Oficina",
                "bluetooth":null,
                "wifi":
                    {
                        "mac":"7C:F6:****:62",
                        "wifi_ssid":"DunderMifflin",
                        "lan_ip_addr":"200.*****”
                    },
                    "product":
                    {
                        "id":"1bb81bed-**********ac130019",
                        "name":"Lumos 2.0 White \u0026 Color",
                        "region":"ALL",
                        "default_name":"My Smart Bulb",
                        "icon_url":"https://d1teb1w17vl5yo.cloudfront.net/eufyhome/products/T1018_addProductIcon.png",
                        "category":"Home",
                        "appliance":"Lights",
                        "connect_type":1,
                        "description":"T1018 Lumos 2.0 White \u0026 Color, connected via EufyHome",
                        "product_code":"T1018",
                        "wifi_ssid_prefix":"eufy Lumos T1018 Bulb",
                        "wifi_ssid_prefix_full":"eufy Lumos T1018 Bulb-",
                        "index":13,
                        "create_time":1495421661,
                        "update_time":1495421661,
                        "is_show":false,
                        "tuya_pid":"thmo9***rjrcyqmm"
                    },
                    "user_id”:”***”,
                    "owner_info":null,
                    "home_id”:”****”,
                    "home_name":"",
                    "room_id":"008870e3-5(******a4",
                    "room_name":"Bedroom",
                    "connect_type":1,
                    "grant_by":0,
                    "software_version":"1.3.2",
                    "index":0,
                    "device_key":"",
                    "create_time":1642789044,
                    "update_time":1642789081,
                    "hardware_version":"",
                    "local_code":"",
                    "setting":{
                        "id":"",
                        "device_id":"",
                        "is_default":true}
                    },
                    "group":null
                }
            ],
                "global_config":{"enabled_multi_color_modes":[0,1,2,3]}}%

**Comment by sebmos** [comment]
That was really helpful, thanks. The reason it's not supported is that it does not have a "local_code", which is needed to connect to the device. It appears this light bulb doesn't support local network-based connectivity.
The server-based control method used by the app as a fallback (and I assume for your light bulb) has not been replicated by third-party developers, as far as I know.

Sorry - nothing I can do about that!

**Comment by t3b4n** [comment]
Ouch, bad news. I tried to use tuya homebridge plugin as well and it was also a failed attempt. The tuya API has the same issue where it's not able to see any devices added in my account (but I'm able to control the bulb from Tuya Smart app).
