### ISSUE TITLE
Unknown device model

### ISSUE THREAD

**Issue by dallombra** [sebmos/node-eufy-api#3]
Hi, I’ve just tried to install the homebridge plugin (https://www.npmjs.com/package/homebridge-eufy). After restarting homebridge I got the following error: “Unknown device model “T2103”. The only device in my eufy account is the Robovac 11c. Are there any plans to support this kind of devices?

**Comment by sebmos** [comment]
Hey @dallombra,

The only devices currently supported are the ones listed on the NPM package - the light bulbs, power plugs & switches.

There's currently no plan to support the Robovac or other devices, although I'd be happy to accept contributions that add support!
