### ISSUE TITLE
Feature Request: Add the ability to use Eufy’s new security products

### ISSUE THREAD

**Issue by David-Alton** [sebmos/node-eufy-api#7]
Eufy recently released new security products (cameras, door sensors, and doorbells). Would it be possible to add those to this API?

**Comment by sebmos** [comment]
Hey - I don't have any of these devices, so I don't know/couldn't verify. It'd be brilliant if somebody could add support, though!

**Comment by ageisen2000** [comment]
I have a Eufy security doorbell camera. Is there something I can do to help you with this?
